//
// Created by Carlos Torres on 8/22/20.
//

#ifndef DATA_STRUCTURES_AND_ALGORITHMS_MERGE_SORT_PTHREAD_H
#define DATA_STRUCTURES_AND_ALGORITHMS_MERGE_SORT_PTHREAD_H

int* merge_sort_pthread(int*, int);

#endif //DATA_STRUCTURES_AND_ALGORITHMS_MERGE_SORT_PTHREAD_H
