//
// Created by Carlos Torres on 8/2/20.
//

#ifndef DATA_STRUCTURES_AND_ALGORITHMS_MERGE_SORT_H
#define DATA_STRUCTURES_AND_ALGORITHMS_MERGE_SORT_H

int* merge_sort(int*, int);

#endif //DATA_STRUCTURES_AND_ALGORITHMS_MERGE_SORT_H
